package com.hehua.framework.message;

import java.io.Serializable;
import java.text.MessageFormat;

/**
 * Auto generated by pandora dict system
 * 
 * @Author Pandora
 * @Date 2013-03-18 11:15:32
 */
public class Message implements Serializable {

    private static final long serialVersionUID = 1L;

    /** 编号 **/
    private int id;

    /** 代码 **/
    private String code;

    /** 模板 **/
    private String message;

    /** 注释 **/
    private String comment;

    public Message() {
        super();
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    private MessageFormat format;

    private MessageFormat getFormat() {
        if (format != null) {
            return format;
        }
        format = new MessageFormat(message);
        return format;
    }

    public synchronized String format(Object[] args) {
        return getFormat().format(args);
    }

    @Override
    public String toString() {
        return "MessageTemplate [id=" + id + ", code=" + code + ", message=" + message
                + ", comment=" + comment + "]";
    }

}
